//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketRaising.Data_Component
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketNo { get; set; }
        public int EmpId { get; set; }
        public string SystemNo { get; set; }
        public string RaisedTime { get; set; }
        public string ResolvedTime { get; set; }
        public string ProblemStatement { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string Status { get; set; }
    
        public virtual tktEmployee tktEmployee { get; set; }
        public virtual tktEmployee tktEmployee1 { get; set; }
    }
}
